# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import digital_twin_pb2 as digital__twin__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in digital_twin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DigitalTwinStub(object):
    """Digital Twin gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/polaris.digitaltwin.DigitalTwin/Query',
                request_serializer=digital__twin__pb2.QueryRequest.SerializeToString,
                response_deserializer=digital__twin__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Simulate = channel.unary_unary(
                '/polaris.digitaltwin.DigitalTwin/Simulate',
                request_serializer=digital__twin__pb2.SimulationRequest.SerializeToString,
                response_deserializer=digital__twin__pb2.SimulationResponse.FromString,
                _registered_method=True)
        self.Diagnose = channel.unary_unary(
                '/polaris.digitaltwin.DigitalTwin/Diagnose',
                request_serializer=digital__twin__pb2.DiagnosisRequest.SerializeToString,
                response_deserializer=digital__twin__pb2.DiagnosisResponse.FromString,
                _registered_method=True)
        self.Manage = channel.unary_unary(
                '/polaris.digitaltwin.DigitalTwin/Manage',
                request_serializer=digital__twin__pb2.ManagementRequest.SerializeToString,
                response_deserializer=digital__twin__pb2.ManagementResponse.FromString,
                _registered_method=True)


class DigitalTwinServicer(object):
    """Digital Twin gRPC service definition
    """

    def Query(self, request, context):
        """Query current or historical system state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simulate(self, request, context):
        """Perform predictive simulation ("what-if" analysis)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Diagnose(self, request, context):
        """Perform root cause analysis and diagnosis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Manage(self, request, context):
        """Manage Digital Twin lifecycle and introspection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DigitalTwinServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=digital__twin__pb2.QueryRequest.FromString,
                    response_serializer=digital__twin__pb2.QueryResponse.SerializeToString,
            ),
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=digital__twin__pb2.SimulationRequest.FromString,
                    response_serializer=digital__twin__pb2.SimulationResponse.SerializeToString,
            ),
            'Diagnose': grpc.unary_unary_rpc_method_handler(
                    servicer.Diagnose,
                    request_deserializer=digital__twin__pb2.DiagnosisRequest.FromString,
                    response_serializer=digital__twin__pb2.DiagnosisResponse.SerializeToString,
            ),
            'Manage': grpc.unary_unary_rpc_method_handler(
                    servicer.Manage,
                    request_deserializer=digital__twin__pb2.ManagementRequest.FromString,
                    response_serializer=digital__twin__pb2.ManagementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polaris.digitaltwin.DigitalTwin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polaris.digitaltwin.DigitalTwin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DigitalTwin(object):
    """Digital Twin gRPC service definition
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polaris.digitaltwin.DigitalTwin/Query',
            digital__twin__pb2.QueryRequest.SerializeToString,
            digital__twin__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polaris.digitaltwin.DigitalTwin/Simulate',
            digital__twin__pb2.SimulationRequest.SerializeToString,
            digital__twin__pb2.SimulationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Diagnose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polaris.digitaltwin.DigitalTwin/Diagnose',
            digital__twin__pb2.DiagnosisRequest.SerializeToString,
            digital__twin__pb2.DiagnosisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Manage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polaris.digitaltwin.DigitalTwin/Manage',
            digital__twin__pb2.ManagementRequest.SerializeToString,
            digital__twin__pb2.ManagementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
